import type { Metadata } from "next";

import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import NavBar from "@/components/NavBar";

export const metadata: Metadata = {
  title: "Dev Overflow",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <div className="max-w-8xl mx-auto overflow-hidden">
            <NavBar />
            <main>{children}</main>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
