import type { Metadata } from "next";
import "./globals.css";
import "../styles/prism.css";
import ThemeProvider from "@/src/components/Theme";
import { Toaster } from "../components/ui/toaster";
import { Suspense } from "react";
import AuthProvider from "@/src/components/AuthProvider";
import { getCurrentUser } from "@/src/lib/auth/session";
import AppShell from "@/src/components/AppShell";
import NavBar from "@/src/components/NavBar";
import LeftSideBar from "@/src/components/LeftSideBar";
import RightSideBar from "@/src/components/RightSideBar";
import { Geist } from "next/font/google";
import { cn } from "@/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
  title: "Dev Overflow",
  description: "Generated by create next app",
  icons: "/assets/images/logo.svg",
};

export const dynamic = "force-dynamic";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialUserPromise = getCurrentUser();

  return (
    <html lang="en" className={cn("font-sans", geist.variable)}>
      <body
        className="bg-background text-foreground"
        style={
          {
            "--font-poppins":
              '"Aptos", "Segoe UI Variable Display", "Segoe UI", sans-serif',
            "--font-noto-serif":
              '"Iowan Old Style", "Palatino Linotype", "Book Antiqua", serif',
          } as React.CSSProperties
        }
      >
        <Suspense>
          <LayoutContent initialUserPromise={initialUserPromise}>
            {children}
          </LayoutContent>
        </Suspense>
      </body>
    </html>
  );
}

async function LayoutContent({
  children,
  initialUserPromise,
}: {
  children: React.ReactNode;
  initialUserPromise: ReturnType<typeof getCurrentUser>;
}) {
  const user: any = await initialUserPromise;

  return (
    <AuthProvider
      initialUser={
        user
          ? {
              _id: user._id.toString(),
              name: user.name,
              email: user.email,
              picture: user.picture,
            }
          : null
      }
    >
      <ThemeProvider>
        <AppShell
          standalone={children}
          shell={
            <div className="mx-auto flex min-h-screen w-full max-w-[1600px] flex-col px-4 pb-8 md:px-6 xl:px-8">
              <NavBar />
              <div className="grid flex-1 grid-cols-1 gap-6 lg:grid-cols-[260px_minmax(0,1fr)_300px]">
                <LeftSideBar />
                <main className="min-w-0">{children}</main>
                <RightSideBar />
              </div>
            </div>
          }
        />
        <Toaster />
      </ThemeProvider>
    </AuthProvider>
  );
}
